name: Terraform Destroy - Dev

on:
  # manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  terraform-destroy-dev:
    runs-on: ubuntu-latest

    defaults:
      run:
        # same dir you used in deploy workflow
        working-directory: aws-infra-terraform/aws-2tier/envs/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.5   # or whatever you used before

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform init
        run: terraform init

      - name: Terraform destroy
        run: terraform destroy -auto-approve -var-file=terraform.tfvars
